repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
      - id: nbdev_clean
        language: python
        additional_dependencies: ["setuptools"]
      - id: nbdev_export
        language: python
        additional_dependencies: ["setuptools"]
